### ISSUE TITLE
Error in API call when there's nothing to convert

### ISSUE THREAD

**Issue by Rockerby** [Lantzify/auto-block-list#3]
**Describe the bug**
Loading up the main page within settings throws a 500 (from /umbraco/backoffice/api/AutoBlockListApi/GetAllContentWithNC?page=0). Looks like this is an issue when there are no applicable data types to convert.

![image](https://github.com/Lantzify/auto-block-list/assets/5808078/c424cf1b-a6f9-4ea5-aaf4-cfe3693f400c)

**To Reproduce**
1. Create a new Umbraco 13.2.2 instance (not tested on other versions)
2. Install Umbraco.TheStarterKit (just for dummy content)
3. Install your package
4. Go to Settings
5. Click the Auto Block List option in the left
6. See the spinner and console error

**Expected behavior**
To show a "nothing to convert" page

**Comment by Lantzify** [comment]
Hello @Rockerby! Thank you so much for taking the time to report this! It really means the world to me!

I've gone ahead and added the necessary things to fix this, and updated the package to version 1.1.0! Thank you so much for your help!

#H5YR 🙌
